# Generated by Django 4.2.5 on 2023-10-01 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category_products_price_alter_products_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='nome',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('ALIMENTOS', 'ALIMENTOS'), ('LIMPEZA', 'LIMPEZA'), ('ELETRONICOS', 'ELETRONICOS'), ('LIVROS_MEDIA', 'LIVROS_MEDIA'), ('BELEZA', 'BELEZA'), ('FERRAMENTAS', 'FERRAMENTAS'), ('AUTOMOVEIS', 'AUTOMOVEIS'), ('ESPORTES', 'ESPORTES'), ('SAUDE_BEMESTAR', 'SAUDE_BEMESTAR'), ('JARDINAGEM', 'JARDINAGEM'), ('INDEFINIDO', 'INDEFINIDO')], default='INDEFINIDO', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
