# Generated by Django 4.2.5 on 2023-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_nome_products_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('ALIMENTOS', 'ALIMENTOS'), ('BELEZA', 'BELEZA'), ('ELETRONICOS', 'ELETRONICOS'), ('ESPORTES', 'ESPORTES'), ('FERRAMENTAS', 'FERRAMENTAS'), ('HIGIENE', 'HIGIENE'), ('JARDINAGEM', 'JARDINAGEM'), ('LIMPEZA', 'LIMPEZA'), ('LIVROS_MEDIA', 'LIVROS_MEDIA'), ('SAUDE_BEMESTAR', 'SAUDE_BEMESTAR'), ('AUTOMOVEIS', 'AUTOMOVEIS'), ('INDEFINIDO', 'INDEFINIDO')], default='INDEFINIDO', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
